# Generated by Django 4.0.2 on 2022-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_community_new_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_new',
            name='message',
            field=models.TextField(max_length=400),
        ),
    ]
