# Generated by Django 4.0.2 on 2022-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_community_new_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_new',
            name='links',
            field=models.JSONField(default=[{'link': 'link goes here', 'message': 'link message'}]),
        ),
    ]
