# Generated by Django 4.0.2 on 2022-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(default='https://picsum.photos/1000/1000', upload_to='images'),
        ),
    ]
