# Generated by Django 4.0.2 on 2022-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='https://picsum.photos/1000/1000', max_length=200),
        ),
    ]
